### ISSUE TITLE
Location of hostname on Linux/MacOS is /bin/hostname as opposed to /usr/bin/hostname

### ISSUE THREAD

**Issue by JupiterJones** [GsDevKit/GsDevKit_stones#1]
```
createStone.solo --root=/Users/jupiter/Documents/Development/GemStone/GsDevKit/myStones/test1 --projectsHome=/Users/jupiter/Documents/Development/GemStone/GsDevKit/myStones/git --template=minimal --registry=puppy test1 3.6.5
Error: invalid path for fork, errno=2,ENOENT, The file or directory specified cannot be found, path: /usr/bin/hostname
```

**Comment by martinmcclure** [comment]
On recent Linux distributions (including Ubuntu, RedHat, Gentoo) /bin is a symlink to /usr/bin, so either /bin/hostname or /usr/bin/hostname should work. On new Macs /bin and /usr/bin are not unified. Most things are in /usr/bin, but hostname is, as @JupiterJones says, in /bin.

**Comment by dalehenrich** [comment]
Cool ... that makes things simpler :)

**Comment by dalehenrich** [comment]
hold

**Comment by dalehenrich** [comment]
hold your horses ... I misread Martin's message ... they ARE NOT unified and I need to adjust only the location of hostname ...
